# Generated by Django 5.2.8 on 2025-11-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='is_class_teacher',
        ),
    ]
