# Generated by Django 4.2.26 on 2026-06-17 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_schooldivision_classlevel_division_classstream'),
        ('accounts', '0003_remove_teacherprofile_is_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff_role',
            field=models.CharField(choices=[('proprietor', 'Proprietor/Proprietress'), ('headmaster', 'Headmaster/Headmistress'), ('assistant_head', 'Assistant Head'), ('manager', 'School Manager'), ('admin', 'Administrator'), ('accountant', 'Accountant'), ('secretary', 'Secretary'), ('librarian', 'Librarian'), ('security', 'Security'), ('cleaner', 'Cleaner'), ('cook', 'Cook'), ('driver', 'Driver'), ('other', 'Other')], default='admin', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.classstream'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_type',
            field=models.CharField(choices=[('administrative', 'Administrative'), ('leadership', 'Leadership'), ('finance', 'Finance'), ('support', 'Support'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role__in': ['admin', 'proprietor', 'headmaster', 'assistant_head', 'manager', 'non_teaching']}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('proprietor', 'Proprietor'), ('headmaster', 'Headmaster/Headmistress'), ('assistant_head', 'Assistant Head'), ('manager', 'School Manager'), ('teacher', 'Teacher'), ('non_teaching', 'Non-Teaching Staff'), ('student', 'Student'), ('parent', 'Parent/Guardian')], max_length=20),
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=20, unique=True)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], default='guardian', max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_primary_contact', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, related_name='parent_profiles', to='accounts.studentprofile')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
                'db_table': 'parent_profiles',
            },
        ),
    ]
