# Generated by Django 4.2.26 on 2026-06-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffprofile_department_staffprofile_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_level',
            field=models.CharField(choices=[('early_years', 'Early Years'), ('primary', 'Primary'), ('jhs', 'Junior High School'), ('all_levels', 'All Levels')], default='primary', max_length=20),
        ),
    ]
