# Generated by Django 5.2.8 on 2025-11-09 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='form_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_levels_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classlevel'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_class_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classlevel'),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='uploaded_by',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='subjects',
            field=models.ManyToManyField(related_name='class_levels', through='academics.ClassSubject', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='result',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='subjects_code_3f80fa_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['category'], name='subjects_categor_8c1690_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active'], name='subjects_is_acti_960049_idx'),
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['class_level', 'academic_year'], name='class_subje_class_l_a202a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_level', 'subject', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='classlevel',
            index=models.Index(fields=['code'], name='class_level_code_b1d8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='classlevel',
            index=models.Index(fields=['is_active'], name='class_level_is_acti_cb1a31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('name', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student', 'term'], name='results_student_fbef3d_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['subject', 'term'], name='results_subject_d194f6_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['is_published'], name='results_is_publ_99e7b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'subject', 'term')},
        ),
    ]
